// src/Treeselect.vue
<template>
  <div class="vue-treeselect">
    <div ref="treeselectContainerRef" />
    <div
      ref="treeselectAfterListSlotRef"
      class="treeselect__after-list-slot"
    >
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, onMounted, onUnmounted, PropType, ref, toRaw, watch } from 'vue'
import Treeselect, { IconsType, DirectionType, OptionType, ValueInputType, TagsSortItem } from 'treeselectjs'

export { type IconsType, type DirectionType, type OptionType, type TagsSortItem } from 'treeselectjs'

export type TreeselectValue = ValueInputType

const keysWithoutRender = ['modelValue', 'options', 'id', 'iconElements']

export default defineComponent({
  name: 'VueTreeselect',
  props: {
    modelValue: {
      type: [Array, Number, String] as PropType<TreeselectValue>,
      default: () => []
    },
    options: {
      type: Array as PropType<OptionType[]>,
      default: () => []
    },
    openLevel: {
      type: Number,
      default: 0
    },
    appendToBody: {
      type: Boolean,
      default: false
    },
    alwaysOpen: {
      type: Boolean,
      default: false
    },
    showTags: {
      type: Boolean,
      default: true
    },
    tagsCountText: {
      type: String,
      default: 'elements selected'
    },
    tagsSortFn: {
      type: Function as PropType<(a: TagsSortItem, b: TagsSortItem) => number> | null,
      default: null
    },
    clearable: {
      type: Boolean,
      default: true
    },
    searchable: {
      type: Boolean,
      default: true
    },
    placeholder: {
      type: String,
      default: 'Select...'
    },
    grouped: {
      type: Boolean,
      default: true
    },
    disabled: {
      type: Boolean,
      default: false
    },
    emptyText: {
      type: String,
      default: 'No results found...'
    },
    staticList: {
      type: Boolean,
      default: false
    },
    id: {
      type: String,
      default: ''
    },
    ariaLabel: {
      type: String,
      default: ''
    },
    isSingleSelect: {
      type: Boolean,
      default: false
    },
    showCount: {
      type: Boolean,
      default: false
    },
    isGroupedValue: {
      type: Boolean,
      default: false
    },
    disabledBranchNode: {
      type: Boolean,
      default: false
    },
    direction: {
      type: String as PropType<DirectionType>,
      default: 'auto'
    },
    expandSelected: {
      type: Boolean,
      default: false
    },
    saveScrollPosition: {
      type: Boolean,
      default: true
    },
    isIndependentNodes: {
      type: Boolean,
      default: false
    },
    rtl: {
      type: Boolean,
      default: false
    },
    isBoostedRendering: {
      type: Boolean,
      default: false
    },
    listClassName: {
      type: String,
      default: ''
    },
    iconElements: {
      type: Object as PropType<Partial<IconsType>>,
      default: () => ({})
    }
  },
  emits: ['input', 'open', 'close', 'name-change', 'search', 'open-close-group', 'update:modelValue'],
  setup(props, { emit }) {
    const treeselectContainerRef = ref<HTMLElement | null>(null)
    const treeselectAfterListSlotRef = ref<HTMLElement | null>(null)
    const treeselect = ref<Treeselect | null>(null)

    const onInput = (modelValue: TreeselectValue) => {
      emit('update:modelValue', modelValue)
      emit('input', modelValue)
    }
    const onOpen = (value: TreeselectValue) => emit('open', value)
    const onClose = (value: TreeselectValue) => emit('close', value)
    const onNameChange = (name: string) => emit('name-change', name)
    const onSearch = (value: string) => emit('search', value)
    const onOpenCloseGroup = (groupId: TreeselectValue, isClosed: boolean) =>
      emit('open-close-group', {
        groupId,
        isClosed
      })

    const valueString = computed(() => JSON.stringify(props.modelValue))
    const optionsArrayString = computed(() => JSON.stringify(props.options))
    const iconsElementsString = computed(() => JSON.stringify(props.iconElements))

    watch(
      () => props,
      (newProps) => {
        if (treeselect.value) {
          const rawTreeselect = toRaw(treeselect.value)
          const rawProps = toRaw(newProps)
          let isAnyChanged = false

          Object.keys(rawProps).forEach((key) => {
            // @ts-ignore
            const isTheSameValue = rawProps[key] === rawTreeselect[key]
            const isWithRender = keysWithoutRender.includes(key)

            if (!isWithRender && !isTheSameValue) {
              // @ts-ignore
              rawTreeselect[key] = rawProps[key]
              isAnyChanged = true
            }
          })

          if (isAnyChanged) {
            rawTreeselect.mount()
          }
        }
      },
      { deep: true }
    )

    watch(
      () => valueString.value,
      () => {
        if (treeselect.value) {
          const rawTreeselect = toRaw(treeselect.value)
          rawTreeselect.updateValue(props.modelValue)
        }
      }
    )

    watch(
      () => props.id,
      (newId) => {
        if (treeselect.value) {
          const rawTreeselect = toRaw(treeselect.value)
          const isTreeselectIdExist = rawTreeselect.id || newId

          if (isTreeselectIdExist) {
            rawTreeselect.id = newId ?? ''
            rawTreeselect.mount()
          }
        }
      }
    )

    watch(
      () => optionsArrayString.value,
      () => {
        if (treeselect.value) {
          const rawTreeselect = toRaw(treeselect.value)
          rawTreeselect.options = props.options
          rawTreeselect.mount()

          // Update value after options change
          rawTreeselect.updateValue(props.modelValue)
        }
      }
    )

    watch(
      () => iconsElementsString.value,
      () => {
        if (treeselect.value) {
          const rawTreeselect = toRaw(treeselect.value)
          rawTreeselect.iconElements = {
            ...rawTreeselect.iconElements,
            ...props.iconElements
          }
          rawTreeselect.mount()
        }
      }
    )

    onMounted(() => {
      if (!treeselectContainerRef.value) {
        throw new Error('Treeselect container ref is not defined')
      }

      treeselect.value = new Treeselect({
        parentHtmlContainer: treeselectContainerRef.value,
        value: props.modelValue,
        options: props.options,
        openLevel: props.openLevel,
        appendToBody: props.appendToBody,
        alwaysOpen: props.alwaysOpen,
        showTags: props.showTags,
        tagsCountText: props.tagsCountText,
        tagsSortFn: props.tagsSortFn,
        clearable: props.clearable,
        searchable: props.searchable,
        placeholder: props.placeholder,
        grouped: props.grouped,
        disabled: props.disabled,
        emptyText: props.emptyText,
        staticList: props.staticList,
        id: props.id,
        ariaLabel: props.ariaLabel,
        isSingleSelect: props.isSingleSelect,
        showCount: props.showCount,
        isGroupedValue: props.isGroupedValue,
        disabledBranchNode: props.disabledBranchNode,
        direction: props.direction,
        expandSelected: props.expandSelected,
        saveScrollPosition: props.saveScrollPosition,
        isIndependentNodes: props.isIndependentNodes,
        rtl: props.rtl,
        isBoostedRendering: props.isBoostedRendering,
        listClassName: props.listClassName,
        inputCallback: onInput,
        openCallback: onOpen,
        closeCallback: onClose,
        nameChangeCallback: onNameChange,
        searchCallback: onSearch,
        openCloseGroupCallback: onOpenCloseGroup,
        // We need a HTMLElement as a prop here. It is an additional component at the end of list.
        // We gets HTMLElement from refs. Vue events work fine.
        listSlotHtmlComponent: treeselectAfterListSlotRef.value ?? null,
        iconElements: props.iconElements
      })
    })

    onUnmounted(() => {
      if (treeselect.value) {
        const rawTreeselect = toRaw(treeselect.value)
        rawTreeselect.destroy()
      }
    })

    return {
      treeselectContainerRef,
      treeselectAfterListSlotRef
    }
  }
})
</script>

<style lang="css">
@import 'treeselectjs/dist/treeselectjs.css';

.vue-treeselect {
  display: block;
  width: 100%;
  box-sizing: border-box;
}
</style>

// packages/react-treeselectjs/src/Treeselect.tsx
// Keep React in scope for JSX/runtime compatibility (e.g. older bundlers or tooling)
// biome-ignore lint/correctness/noUnusedImports: React may be required by JSX transform or tooling
import React, { type PropsWithChildren, useLayoutEffect, useRef } from 'react'
import TreeselectJS, { type IconsType, type ValueInputType, type ITreeselectParams } from 'treeselectjs'
import 'treeselectjs/dist/treeselectjs.css'

export type { DirectionType, IconsType, OptionType } from 'treeselectjs'

export type TreeselectValue = ValueInputType

interface TreeselectReactParams extends ITreeselectParams {
  onInput?: (value: TreeselectValue) => void
  onOpen?: (value: TreeselectValue) => void
  onClose?: (value: TreeselectValue) => void
  onNameChange?: (name: string) => void
  onSearch?: (value: string) => void
  onOpenCloseGroup?: (groupId: TreeselectValue, isClosed: boolean) => void
}

type TreeselectOmittedParams =
  | 'parentHtmlContainer'
  | 'listSlotHtmlComponent'
  | 'inputCallback'
  | 'openCallback'
  | 'closeCallback'
  | 'nameChangeCallback'
  | 'searchCallback'
  | 'openCloseGroupCallback'

export type TreeselectProps = Omit<TreeselectReactParams, TreeselectOmittedParams>

const isDifferentValues = (firstValue: unknown, secondValue: unknown) => {
  return JSON.stringify(firstValue) !== JSON.stringify(secondValue)
}

const isDifferentIconElements = (firstValue?: Partial<IconsType>, secondValue?: Partial<IconsType>) => {
  const firstIcons = firstValue ?? {}
  const secondIcons = secondValue ?? {}
  const iconKeys = new Set([...Object.keys(firstIcons), ...Object.keys(secondIcons)] as (keyof IconsType)[])

  return Array.from(iconKeys).some((key) => firstIcons[key] !== secondIcons[key])
}

const cloneIconElements = (iconElements?: Partial<IconsType>) => {
  return iconElements ? { ...iconElements } : undefined
}

const getResolvedTreeselectProps = (props: PropsWithChildren<TreeselectProps>) => {
  const appendToBody = props.appendToBody ?? false
  const disabled = props.disabled ?? false

  return {
    options: props.options ?? [],
    openLevel: props.openLevel ?? 0,
    appendToBody,
    alwaysOpen: !!(props.alwaysOpen && !disabled),
    showTags: props.showTags ?? true,
    tagsCountText: props.tagsCountText ?? 'elements selected',
    tagsSortFn: props.tagsSortFn ?? null,
    clearable: props.clearable ?? true,
    searchable: props.searchable ?? true,
    placeholder: props.placeholder ?? 'Select...',
    grouped: props.grouped ?? true,
    isGroupedValue: props.isGroupedValue ?? false,
    disabled,
    emptyText: props.emptyText ?? 'No results found...',
    staticList: !!(props.staticList && !appendToBody),
    id: props.id ?? '',
    ariaLabel: props.ariaLabel ?? '',
    isSingleSelect: props.isSingleSelect ?? false,
    showCount: props.showCount ?? false,
    disabledBranchNode: props.disabledBranchNode ?? false,
    direction: props.direction ?? 'auto',
    expandSelected: props.expandSelected ?? false,
    saveScrollPosition: props.saveScrollPosition ?? true,
    isIndependentNodes: props.isIndependentNodes ?? false,
    rtl: props.rtl ?? false,
    listClassName: props.listClassName ?? '',
    isBoostedRendering: props.isBoostedRendering ?? false,
  } satisfies Pick<
    TreeselectJS,
    | 'options'
    | 'openLevel'
    | 'appendToBody'
    | 'alwaysOpen'
    | 'showTags'
    | 'tagsCountText'
    | 'tagsSortFn'
    | 'clearable'
    | 'searchable'
    | 'placeholder'
    | 'grouped'
    | 'isGroupedValue'
    | 'disabled'
    | 'emptyText'
    | 'staticList'
    | 'id'
    | 'ariaLabel'
    | 'isSingleSelect'
    | 'showCount'
    | 'disabledBranchNode'
    | 'direction'
    | 'expandSelected'
    | 'saveScrollPosition'
    | 'isIndependentNodes'
    | 'rtl'
    | 'listClassName'
    | 'isBoostedRendering'
  >
}

type ResolvedTreeselectProps = ReturnType<typeof getResolvedTreeselectProps>

const getResolvedTreeselectCallbacks = (props: PropsWithChildren<TreeselectProps>) => {
  return {
    inputCallback: props.onInput,
    openCallback: props.onOpen,
    closeCallback: props.onClose,
    nameChangeCallback: props.onNameChange,
    searchCallback: props.onSearch,
    openCloseGroupCallback: props.onOpenCloseGroup,
  } satisfies Pick<
    TreeselectJS,
    | 'inputCallback'
    | 'openCallback'
    | 'closeCallback'
    | 'nameChangeCallback'
    | 'searchCallback'
    | 'openCloseGroupCallback'
  >
}

const remountPropKeys = [
  'openLevel',
  'appendToBody',
  'alwaysOpen',
  'showTags',
  'tagsCountText',
  'tagsSortFn',
  'clearable',
  'searchable',
  'placeholder',
  'grouped',
  'isGroupedValue',
  'disabled',
  'emptyText',
  'staticList',
  'id',
  'ariaLabel',
  'isSingleSelect',
  'showCount',
  'disabledBranchNode',
  'direction',
  'expandSelected',
  'saveScrollPosition',
  'isIndependentNodes',
  'rtl',
  'listClassName',
  'isBoostedRendering',
] as const satisfies readonly (keyof ResolvedTreeselectProps)[]

const callbackPropKeys = [
  'inputCallback',
  'openCallback',
  'closeCallback',
  'nameChangeCallback',
  'searchCallback',
  'openCloseGroupCallback',
] as const satisfies readonly (keyof ReturnType<typeof getResolvedTreeselectCallbacks>)[]

const Treeselect = (props: PropsWithChildren<TreeselectProps>) => {
  const treeselectRef = useRef<HTMLDivElement | null>(null)
  const treeselectAfterListSlotRef = useRef<HTMLDivElement | null>(null)
  const treeselect = useRef<TreeselectJS | null>(null)
  const previousIconElements = useRef(cloneIconElements(props.iconElements))

  // Mount once, destroy on unmount; props synced below after React commits.
  // useLayoutEffect (not useEffect) so destroy() runs synchronously before React removes the
  // fragment's DOM nodes - TreeselectJS reparents listSlotHtmlComponent into the list markup,
  // and a deferred (passive) cleanup would run after React already tried to remove that node
  // from its original position, throwing a NotFoundError.
  // biome-ignore lint/correctness/useExhaustiveDependencies: intentional — run only on mount ([]), not on every prop change
  useLayoutEffect(() => {
    const afterListSlotOriginalParent = treeselectAfterListSlotRef.current?.parentElement ?? null

    treeselect.current = new TreeselectJS({
      parentHtmlContainer: treeselectRef.current as HTMLDivElement,
      listSlotHtmlComponent: treeselectAfterListSlotRef.current as HTMLDivElement,
      ...getResolvedTreeselectProps(props),
      ...getResolvedTreeselectCallbacks(props),
      value: props.value,
      iconElements: props.iconElements,
    })

    return () => {
      // TreeselectJS moves treeselectAfterListSlotRef.current into the dropdown's own
      // markup while open/mounted. Put it back under its original React-rendered parent
      // before destroy() runs, so React's own unmount can still find and remove it from
      // where it originally placed it (otherwise removeChild throws NotFoundError).
      if (treeselectAfterListSlotRef.current && afterListSlotOriginalParent) {
        afterListSlotOriginalParent.appendChild(treeselectAfterListSlotRef.current)
      }

      treeselect.current?.destroy()
      treeselect.current = null
    }
  }, [])

  useLayoutEffect(() => {
    if (!treeselect.current) {
      return
    }

    const resolvedProps = getResolvedTreeselectProps(props)
    let shouldMount = false
    let shouldUpdateValue = false

    remountPropKeys.forEach((key) => {
      if (treeselect.current && treeselect.current[key] !== resolvedProps[key]) {
        Object.assign(treeselect.current, { [key]: resolvedProps[key] })
        shouldMount = true
      }
    })

    if (isDifferentValues(treeselect.current.options, resolvedProps.options)) {
      treeselect.current.options = resolvedProps.options
      shouldMount = true
      shouldUpdateValue = true
    }

    if (isDifferentIconElements(previousIconElements.current, props.iconElements)) {
      treeselect.current.iconElements = (props.iconElements ?? {}) as IconsType
      previousIconElements.current = cloneIconElements(props.iconElements)
      shouldMount = true
    }

    const resolvedCallbacks = getResolvedTreeselectCallbacks(props)

    callbackPropKeys.forEach((key) => {
      if (treeselect.current && treeselect.current[key] !== resolvedCallbacks[key]) {
        Object.assign(treeselect.current, { [key]: resolvedCallbacks[key] })
      }
    })

    if (shouldMount) {
      treeselect.current.mount()
    }

    if (shouldUpdateValue || isDifferentValues(treeselect.current.value, props.value)) {
      treeselect.current.updateValue(props.value)
    }
  })

  return (
    <>
      <div ref={treeselectRef} />
      <div ref={treeselectAfterListSlotRef} className="treeselect-after-list-slot">
        {props.children}
      </div>
    </>
  )
}

export default Treeselect
